import = ["/home/don/.config/alacritty/catppuccin-mocha.toml"]

[font]
size = 10.5

[font.normal]
family = "JetBrainsMono"                       ## Adeed `Nerd Font` at the end of every family
style = "Regular"

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.italic]
family = "JetBrainsMono"
style = "Italic"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/bash"

[window]
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
